using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Data;
using System.Collections;
using System.Globalization;
using Rochas.DapperRepository.Specification.Annotations;
using Rochas.DapperRepository.Specification.Enums;
using Rochas.DapperRepository.Exceptions;
using Rochas.DapperRepository.Helpers.SQL;

namespace Rochas.DapperRepository.Helpers
{
    public static class EntityReflector
    {
        // ── Caches de reflexão (estáticos, thread-safe) ──────────────────────
        // Tipos de entidade são imutáveis em runtime → cache seguro.
        // Evitam GetCustomAttribute/GetCustomAttributes a cada chamada.

        private static readonly ConcurrentDictionary<Type, string> TableNames = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo> KeyColumns = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> FilterablePropsCache = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> RelatedEntityPropsCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsRelatedEntityCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsAutoGeneratedCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsNotMappedCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, ColumnAttribute> ColumnAnnotations = new();
        private static readonly ConcurrentDictionary<PropertyInfo, RelatedEntityAttribute> RelatedEntityAttributes = new();

        public static Dictionary<object, object> GetPropertiesValueList(object entity, Type entityType, PropertyInfo[] entityProperties, PersistenceAction action, DatabaseEngine? engine = null)
        {
            var objectSQLDataRelation = new Dictionary<object, object>();

            var tableName = GetTableName(entityType, engine);
            if (!string.IsNullOrWhiteSpace(tableName))
                objectSQLDataRelation.Add("TableName", tableName);

            foreach (var prop in entityProperties)
            {
                var isRelated = IsRelatedEntityCache.GetOrAdd(prop, p =>
                    p.GetCustomAttributes().Any(atb => atb is RelatedEntityAttribute));

                if (!isRelated)
                {
                    var isAutoGenerated = IsAutoGeneratedCache.GetOrAdd(prop, p =>
                        p.GetCustomAttributes().Any(atb => atb is AutoGeneratedAttribute));

                    var isNotMapped = IsNotMappedCache.GetOrAdd(prop, p =>
                        p.GetCustomAttributes().Any(atb => atb is NotMappedAttribute));

                    var columnAnnotation = ColumnAnnotations.GetOrAdd(prop, p =>
                        p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                    var columnName = columnAnnotation?.Name ?? prop.Name;
                    if (engine == DatabaseEngine.PostgreSQL)
                        columnName = columnName.ToLower();

                    var columnValue = prop.GetValue(Convert.ChangeType(entity, entity.GetType()), null);
                    columnValue = FormatSQLInputValue(prop, columnValue, action);

                    if (!((action == PersistenceAction.Add) && isAutoGenerated) && !isNotMapped)
                    {
                        var sqlValueColumn = new KeyValuePair<object, object>(columnName, columnValue);
                        objectSQLDataRelation.Add(prop.Name, sqlValueColumn);
                    }
                }
            }

            return objectSQLDataRelation;
        }

        public static void ValidateListableAttributes(PropertyInfo[] entityProps, string showProperties, out string[] exibitionAttributes)
        {
            IEnumerable<PropertyInfo> listableAttributes = null;
            bool notListableAttribute = false;

            listableAttributes = entityProps.Where(prp => prp.GetCustomAttributes(true).
                                             Where(ca => (ca is ListableAttribute)).Any());

            if (string.IsNullOrWhiteSpace(showProperties))
            {
                exibitionAttributes = new string[listableAttributes.Count()];

                int cont = 0;
                foreach (var listableAttrib in listableAttributes)
                {
                    exibitionAttributes[cont] = listableAttrib.Name;
                    cont++;
                }
            }
            else
            {
                exibitionAttributes = showProperties.Split(',');

                foreach (var attrib in exibitionAttributes)
                {
                    notListableAttribute = !listableAttributes.Contains(attrib.GetType().GetProperty(attrib));
                    if (!notListableAttribute) throw new PropertyNotListableException(attrib); break;
                }
            }
        }

        private static string GetTableName(Type entityType, DatabaseEngine? engine = null)
        {
            var name = TableNames.GetOrAdd(entityType, t =>
            {
                var attr = t.GetCustomAttribute(typeof(TableAttribute)) as TableAttribute;
                if (attr == null) return t.Name;
                return string.IsNullOrWhiteSpace(attr.Schema)
                    ? attr.Name
                    : $"{attr.Schema}.{attr.Name}";
            });

            if (engine == DatabaseEngine.PostgreSQL)
                name = name.ToLower();

            return name;
        }

        private static object FormatSQLInputValue(PropertyInfo column, object columnValue, PersistenceAction action)
        {
            if (columnValue != null)
            {
                var isRequired = column.GetCustomAttributes().Any(atb => atb is RequiredAttribute);

                switch (columnValue.GetType().ToString())
                {
                    case SQL.DataType.Short:
                        if (((short)columnValue == short.MinValue) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Integer:
                        if (((int)columnValue == int.MinValue) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Long:
                        if (((long)columnValue == long.MinValue) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Boolean:
                        columnValue = ((bool)columnValue) ? 1 : 0;
                        break;
                    case SQL.DataType.String:
                        var strValue = columnValue.ToString().Replace("'", "\"");
                        if (strValue != null)
                            columnValue = string.Concat("'", strValue, "'");
                        else
                            columnValue = SqlDefaultValue.Null;

                        break;
                    case SQL.DataType.DateTime:
                        if (!(((DateTime)columnValue).Equals(DateTime.MinValue)))
                        {
                            var dateFormat = (action == PersistenceAction.Add) ?
                                              DateTimeFormat.CompleteDateTime :
                                              DateTimeFormat.NormalDate;

                            columnValue = "'" + ((DateTime)columnValue).ToString(dateFormat) + "'";
                        }
                        else
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Float:
                        if (((float)columnValue == 0) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        else
                            columnValue = columnValue.ToString().Replace(",", ".");

                        break;
                    case SQL.DataType.Double:
                        if (((double)columnValue == 0) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        else
                            columnValue = columnValue.ToString().Replace(",", ".");

                        break;
                    case SQL.DataType.Decimal:
                        if (((decimal)columnValue == 0) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        else
                            columnValue = columnValue.ToString().Replace(",", ".");

                        break;
                }

                if (columnValue.GetType().IsEnum)
                    columnValue = string.Concat("'", columnValue.ToString(), "'");
            }
            else
            {
                columnValue = (action == PersistenceAction.Add) ? SqlDefaultValue.Null : null;
            }

            return columnValue;
        }

        public static PropertyInfo GetKeyColumn(PropertyInfo[] entityProps)
        {
            if (entityProps == null || entityProps.Length == 0) return null;

            var entityType = entityProps[0].DeclaringType;
            return KeyColumns.GetOrAdd(entityType, t =>
                entityProps.FirstOrDefault(prp => prp.GetCustomAttributes().Any(atb => atb is KeyAttribute)));
        }

        public static object GetFilterByPrimaryKey(Type entityType, PropertyInfo[] entityProps, object key)
        {
            var entity = Activator.CreateInstance(entityType);
            if (entity != null)
            {
                var keyColumn = GetKeyColumn(entityProps);
                keyColumn?.SetValue(entity, key);
            }

            return entity;
        }

        public static object GetFilterByFilterableColumns(Type entityType, PropertyInfo[] entityProps, object criteria)
        {
            var entity = Activator.CreateInstance(entityType);
            if (entity != null)
            {
                var filterableProps = FilterablePropsCache.GetOrAdd(entityType, t =>
                    entityProps.Where(prp => prp.GetCustomAttribute(typeof(FilterableAttribute)) != null).ToArray());

                // Envolve com % para LIKE — os wildcards ficam no valor, não no template SQL.
                var likeValue = "%" + criteria + "%";
                foreach (var prop in filterableProps)
                    prop.SetValue(entity, likeValue);
            }

            return entity;
        }

        public static bool IsEmptyObjectValue(object value)
        {
			var strVal = value.ToString().Trim();
			return string.IsNullOrWhiteSpace(strVal)
                || (double.TryParse(strVal, out double fake) && (fake == 0));
		}

        public static void SetFilterPrimaryKey(object entity, PropertyInfo[] entityProps, object filterEntity)
        {
            var entityKeyColumn = GetKeyColumn(entityProps);

            if (entityKeyColumn != null)
            {
                var keyValue = entityKeyColumn.GetValue(entity, null);
                entityKeyColumn.SetValue(filterEntity, keyValue, null);
                entityKeyColumn.SetValue(entity, 0, null);
            }
        }

        public static bool SetChildForeignKeyValue(object parentEntity, PropertyInfo[] parentProps, object childEntity,
                                                   PropertyInfo[] childProps, string foreignKeyPropName)
        {
            bool result = false;

            var parentKey = GetKeyColumn(parentProps);
            var childForeignKey = childProps?.FirstOrDefault(prp => prp.Name.Equals(foreignKeyPropName));

            if ((parentKey != null) && (childForeignKey != null))
            {
                var parentKeyValue = parentKey.GetValue(parentEntity, null);
				if (!IsEmptyObjectValue(parentKeyValue))
				{
					childForeignKey.SetValue(childEntity, parentKeyValue, null);
					result = true;
				}
			}

            return result;
        }

        public static bool SetParentForeignKeyValue(object parentEntity, PropertyInfo[] parentProps, object childEntity,
                                                    PropertyInfo[] childProps, string foreignKeyPropName)
        {
            bool result = false;

            var parentForeignKey = parentProps?.FirstOrDefault(prp => prp.Name.Equals(foreignKeyPropName));
            var childKey = GetKeyColumn(childProps);

            if ((parentForeignKey != null) && (childKey != null))
            {
                var foreignKeyValue = parentForeignKey.GetValue(parentEntity, null);
				if (!IsEmptyObjectValue(foreignKeyValue))
                {
					childKey.SetValue(childEntity, foreignKeyValue, null);
					result = true;
				}
			}

            return result;
        }

        public static IEnumerable<PropertyInfo> GetRelatedEntities(PropertyInfo[] entityProperties)
        {
            if (entityProperties == null || entityProperties.Length == 0)
                return Enumerable.Empty<PropertyInfo>();

            var entityType = entityProperties[0].DeclaringType;
            return RelatedEntityPropsCache.GetOrAdd(entityType, t =>
                entityProperties.Where(prp => prp.GetCustomAttributes(true)
                                    .Any(atb => atb.GetType().Name.Equals("RelatedEntityAttribute"))).ToArray());
        }

        public static RelatedEntityAttribute GetRelatedEntityAttribute(PropertyInfo relatedEntity)
        {
            return RelatedEntityAttributes.GetOrAdd(relatedEntity, p =>
                p.GetCustomAttributes(true)
                 .FirstOrDefault(atb => atb.GetType().Name.Equals("RelatedEntityAttribute")) as RelatedEntityAttribute);
        }

        public static bool MatchKeys(object sourceEntity, PropertyInfo[] entityProps, object destinEntity)
        {
            var entityKey = GetKeyColumn(entityProps);

            return entityKey.GetValue(sourceEntity, null)
                   .Equals(entityKey.GetValue(destinEntity, null));
        }

        public static void SetEntityForeignKey(object parentEntity, object childEntity)
        {
            var parentProps = parentEntity.GetType().GetProperties();
            var parentKey = GetKeyColumn(parentProps);

            var childProps = childEntity.GetType().GetProperties();
            var childForeignKey = GetKeyColumn(childProps);

            if ((parentKey != null) && (childForeignKey != null))
                childForeignKey.SetValue(childEntity, parentKey.GetValue(parentEntity, null), null);
        }

        public static string GetKeyColumnName(PropertyInfo[] entityProps)
        {
            var result = string.Empty;
            var keyProperty = GetKeyColumn(entityProps);
            if (keyProperty != null)
            {
                var columnAnnotation = ColumnAnnotations.GetOrAdd(keyProperty, p =>
                    p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                if (columnAnnotation != null)
                    result = columnAnnotation.Name;
                else
                    result = keyProperty.Name;
            }

            return result;
        }

        public static Dictionary<string, object[]> GetEntityRangeFilter(object entity, PropertyInfo[] entityProps)
        {
            Dictionary<string, object[]> result = null;

            var rangeFilterProps =  entityProps.Where(prp => prp.GetCustomAttributes(true)
                                                 .Any(atb => atb.GetType().Name.Equals("RangeFilterAttribute")
                                                      && !string.IsNullOrWhiteSpace(((RangeFilterAttribute)atb).LinkedRangeProperty)));

            if (rangeFilterProps != null)
            {
                result = new Dictionary<string, object[]>();
                foreach (var prop in rangeFilterProps)
                {
                    var columnAnnotation = ColumnAnnotations.GetOrAdd(prop, p =>
                        p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                    if (columnAnnotation != null)
                    {
                        var columnName = columnAnnotation.Name;
                        var rangePropAttrib = prop.GetCustomAttributes(true)
                                                  .FirstOrDefault(lkp => lkp.GetType().Name.Equals("RangeFilterAttribute"));

                        var linkedRangePropName = ((RangeFilterAttribute)rangePropAttrib).LinkedRangeProperty;
                        var lkdRangeProp = entityProps.FirstOrDefault(lkp => lkp.Name.Equals(linkedRangePropName));
                        if (lkdRangeProp != null)
                        {
                            result.Add(columnName,
                                new object[] { prop.GetValue(entity), lkdRangeProp.GetValue(entity) });
                        }
                        else
                            throw new Exception("Linked range property not found.");
                    }
                }
            }

            return result;
        }

        public static IList CreateTypedList(PropertyInfo child)
        {
            var childListType = child.PropertyType.GetGenericArguments()[0];
            var dynamicManyType = typeof(List<>).MakeGenericType(new Type[] { childListType });
            return (IList)Activator.CreateInstance(dynamicManyType, true);
        }

        public static bool VerifyTableAnnotation(Type entityType)
        {
            var tableName = GetTableName(entityType);
            return !string.IsNullOrWhiteSpace(tableName);
        }

        public static DataTable GetDataTable<T>(ICollection<T> list)
        {
            DataTable table = CreateTable<T>();
            var properties = typeof(T).GetProperties();
            foreach (var item in list)
            {
                DataRow row = table.NewRow();
                foreach (var prop in properties)
                {
                    row[prop.Name] = prop.GetValue(item);
                }
                table.Rows.Add(row);
            }
            return table;
        }
        private static DataTable CreateTable<T>()
        {
            Type entityType = typeof(T);
            DataTable table = new DataTable(entityType.Name);
            var properties = entityType.GetProperties();
            foreach (var prop in properties)
            {
                table.Columns.Add(prop.Name, prop.PropertyType);
            }
            return table;
        }
    }
}
