using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Text.Json;
using System.Reflection;
using System.IO;
using System.Data;
using Microsoft.Data.Sqlite;
using Rochas.DapperRepository.Base;
using Rochas.DapperRepository.Helpers;
using Rochas.SqlWrapper.Helpers;
using Rochas.Data.Specification.Models;
using Rochas.Data.Specification.Enums;
using Rochas.Data.Specification.Interfaces;
using Rochas.Data.Specification.Annotations;

namespace Rochas.DapperRepository
{
	/// <summary>
	/// Base repository with write persistence (Add/Update/Remove) and read (Get/GetSync).
	/// Inherited by GenericRepository (full query builders) and GenericBwoqRepository (BWOQ-only).
	/// </summary>
	public class PersistenceRepository<T> : DatabaseConnection, IPersistenceRepository<T>, IDisposable where T : class
	{
		#region Declarations

		static readonly Type entityType = typeof(T);
		static readonly PropertyInfo[] entityProps = entityType.GetProperties();
		bool _readUncommied;
		ICacheProvider _cacheProvider;
		bool _snakeCaseNaming;
		[ThreadStatic]
		static Dictionary<Type, int> _visitedTypes;

		#endregion

		#region Constructors

		public PersistenceRepository(DatabaseEngine engine, string connectionString, string logPath = null,
			bool keepConnected = false, bool readUncommied = false, bool forceSnakeCase = false,
			ICacheProvider cacheProvider = null, params string[] replicaConnStrings)
			: base(engine, connectionString, logPath, keepConnected, replicaConnStrings)
		{
			_readUncommied = readUncommied;
			_cacheProvider = cacheProvider;
			_snakeCaseNaming = forceSnakeCase;
		}

		public PersistenceRepository(string connectionString, string logPath = null,
			bool keepConnected = false, bool readUncommied = false, bool forceSnakeCase = false,
			ICacheProvider cacheProvider = null, params string[] replicaConnStrings)
			: base(connectionString, logPath, keepConnected, replicaConnStrings)
		{
			_readUncommied = readUncommied;
			_cacheProvider = cacheProvider;
			_snakeCaseNaming = forceSnakeCase;
		}

		public PersistenceRepository(IDbConnection dbConnection, string logPath = null,
			bool keepConnected = false, bool readUncommied = false, bool forceSnakeCase = false,
			ICacheProvider cacheProvider = null, params string[] replicaConnStrings)
			: base(dbConnection, logPath, keepConnected, replicaConnStrings)
		{
			_readUncommied = readUncommied;
			_cacheProvider = cacheProvider;
			_snakeCaseNaming = forceSnakeCase;
		}

		#endregion

		#region Initialize

		public void Initialize(string tableScript, string databaseFileName = null)
		{
			if (!string.IsNullOrWhiteSpace(databaseFileName))
			{
				if (File.Exists(databaseFileName))
					File.Delete(databaseFileName);

				using (var fileConnection = new SqliteConnection($"Data Source={databaseFileName}"))
					fileConnection.Open();
			}

			Connect();
			ExecuteCommand(tableScript);
			Disconnect();
		}

		void IPersistenceRepository<T>.Initialize(string databaseFileName, string tableScript)
			=> Initialize(tableScript, databaseFileName);

		#endregion

		#region Write — Add

		public async Task<int> Add(T entity, bool persistComposition = false)
			=> await AddObject(entity, persistComposition);

		public int AddSync(T entity, bool persistComposition = false)
			=> AddObjectSync(entity, persistComposition);

		public async Task AddRange(IEnumerable<T> entities, bool persistComposition = false)
		{
			try
			{
				StartTransaction();
				foreach (var entity in entities)
					await AddObject(entity, persistComposition);
				CommitTransaction();
			}
			catch (Exception ex)
			{
				CancelTransaction();
				throw ex;
			}
		}

		public void AddRangeSync(IEnumerable<T> entities, bool persistComposition = false)
		{
			try
			{
				StartTransaction();

				var entityList = entities.ToList();
				if (entityList.Count == 0) return;

				var entityType = typeof(T);
				var entityProps = entityType.GetProperties();
				var entityKeyProp = EntityReflector.GetKeyColumn(entityProps);

				var sqlInstruction = EntitySqlParser.ParseEntity(entityList[0], engine, PersistenceAction.Add);

				if (keepConnection || base.Connect())
				{
					foreach (var entity in entityList)
					{
						if (entityKeyProp != null && entityKeyProp.PropertyType == typeof(Guid)
							&& EntityReflector.IsAutoGenerated(entityKeyProp))
						{
							entityKeyProp.SetValue(entity, Guid.NewGuid());
						}

						var id = ExecuteCommand(sqlInstruction);

						if (entityKeyProp != null && entityKeyProp.PropertyType != typeof(Guid) && id > 0)
							entityKeyProp.SetValue(entity, id);

						CleanCacheableData(entity);
					}

					if (!keepConnection) base.Disconnect();
				}

				CommitTransaction();
			}
			catch (Exception ex)
			{
				CancelTransaction();
				throw ex;
			}
		}

		public async Task BulkSqlCreateRange(ICollection<T> entities)
		{
			var entitiesTable = EntityReflector.GetDataTable<T>(entities);
			await ExecuteBulkCommandAsync(entitiesTable);
		}

		public void BulkSqlCreateRangeSync(ICollection<T> entities)
		{
			var entitiesTable = EntityReflector.GetDataTable<T>(entities);
			ExecuteBulkCommand(entitiesTable);
		}

		#endregion

		#region Write — Update

		public async Task<int> Update(T entity, T filterEntity, bool persistComposition = false)
			=> await UpdateObject(entity, filterEntity, persistComposition);

		public int UpdateSync(T entity, T filterEntity, bool persistComposition = false)
			=> UpdateObjectSync(entity, filterEntity, persistComposition);

		#endregion

		#region Write — Remove

		public async Task<int> Remove(T filterEntity)
			=> await RemoveObjects(filterEntity as object);

		public int RemoveSync(T filterEntity)
			=> RemoveObjectsSync(filterEntity as object);

		#endregion

		#region Read — Get

		public async Task<T> Get(object key, bool loadComposition = false)
		{
			if (EntityReflector.IsEmptyObjectValue(key))
				return null;

			var filter = EntityReflector.GetFilterByPrimaryKey(entityType, entityProps, key) as T;
			return await Get(filter, loadComposition);
		}

		public T GetSync(object key, bool loadComposition = false)
		{
			if (EntityReflector.IsEmptyObjectValue(key))
				return null;

			var filter = EntityReflector.GetFilterByPrimaryKey(entityType, entityProps, key) as T;
			return GetSync(filter, loadComposition);
		}

		public async Task<T> Get(T filter, bool loadComposition = false)
			=> await GetObject(filter, loadComposition) as T;

		public T GetSync(T filter, bool loadComposition = false)
			=> GetObjectSync(filter, loadComposition) as T;

		#endregion

		#region Dispose

		public new void Dispose()
		{
			base.Dispose();
			GC.ReRegisterForFinalize(this);
		}

		#endregion

		#region Internal — Read helpers (used by GenericRepository builders + BWOQ)

		internal async Task<object> GetObject(object filter, bool loadComposition = false)
		{
			if (filter == null)
				return null;

			var queryResult = await QueryObjects(filter, PersistenceAction.Get, loadComposition);
			return queryResult?.FirstOrDefault();
		}

		internal object GetObjectSync(object filter, bool loadComposition = false)
		{
			if (filter == null)
				return null;

			return QueryObjectsSync(filter, PersistenceAction.Get, loadComposition)?.FirstOrDefault();
		}

		internal async Task<IEnumerable<object>> QueryObjects(object filterEntity, PersistenceAction action,
			bool loadComposition = false, int recordLimit = 0, bool filterConjunction = false,
			bool onlyListableAttributes = false, string showAttributes = null, string groupAttributes = null,
			string sortAttributes = null, bool orderDescending = false,
			Dictionary<string, DataAggregationType> aggregates = null)
		{
			IEnumerable<object> returnList = null;

			if (IsCacheable(filterEntity))
				returnList = _cacheProvider.Get(filterEntity) as IEnumerable<object>;

			if (returnList == null)
			{
				var sqlParameters = new Dictionary<string, object>();
				var sqlInstruction = EntitySqlParser.ParseEntity(filterEntity, engine, action, filterEntity,
					recordLimit, filterConjunction, onlyListableAttributes, showAttributes, groupAttributes,
					sortAttributes, orderDescending, _readUncommied, sqlParameters, aggregates);

				if (((connection != null) && keepConnection) || base.Connect())
				{
					returnList = await ExecuteQueryAsync(filterEntity.GetType(), sqlInstruction, sqlParameters);
				}

				if (!keepConnection) base.Disconnect();

				if (loadComposition && (returnList != null) && returnList.Any())
				{
					var itemProps = returnList.First().GetType().GetProperties();
					foreach (var item in returnList)
						FillComposition(item, itemProps);
				}

				if ((returnList != null) && IsCacheable(filterEntity))
					_cacheProvider.Put(filterEntity, returnList);
			}

			return returnList;
		}

		internal IEnumerable<object> QueryObjectsSync(object filterEntity, PersistenceAction action,
			bool loadComposition = false, int recordLimit = 0, bool filterConjunction = false,
			bool onlyListableAttributes = false, string showAttributes = null, string groupAttributes = null,
			string sortAttributes = null, bool orderDescending = false,
			Dictionary<string, DataAggregationType> aggregates = null)
		{
			return QueryObjects(filterEntity, action, loadComposition, recordLimit, filterConjunction,
				onlyListableAttributes, showAttributes, groupAttributes, sortAttributes, orderDescending,
				aggregates).GetAwaiter().GetResult();
		}

		internal async Task<int> QueryCountObjects(T filterEntity, bool filterConjunction = false)
		{
			var sqlParameters = new Dictionary<string, object>();
			var sqlInstruction = EntitySqlParser.ParseEntity(filterEntity, engine, PersistenceAction.Query,
				filterEntity, 0, filterConjunction, false, null, null, null, false, _readUncommied, sqlParameters);

			var fromIndex = sqlInstruction.IndexOf(" FROM ", StringComparison.OrdinalIgnoreCase);
			if (fromIndex > 0)
				sqlInstruction = "SELECT COUNT(*) " + sqlInstruction.Substring(fromIndex);

			var orderByIndex = sqlInstruction.IndexOf(" ORDER BY ", StringComparison.OrdinalIgnoreCase);
			if (orderByIndex > 0)
				sqlInstruction = sqlInstruction.Substring(0, orderByIndex);

			var limitIndex = sqlInstruction.IndexOf(" LIMIT ", StringComparison.OrdinalIgnoreCase);
			if (limitIndex > 0)
				sqlInstruction = sqlInstruction.Substring(0, limitIndex);

			if (connection == null || connection.State != ConnectionState.Open)
				Connect();

			var result = await ExecuteCountAsync(sqlInstruction, sqlParameters);

			if (!keepConnection) base.Disconnect();

			return result;
		}

		internal async Task<IEnumerable<object>> QueryObjectsPaged(object filterEntity, PersistenceAction action,
			bool loadComposition = false, int totalCount = 0, int offset = 0, int pageSize = 20,
			bool filterConjunction = false, string groupAttributes = null, string sortAttributes = null,
			bool orderDescending = false, Dictionary<string, DataAggregationType> aggregates = null)
		{
			var sqlParameters = new Dictionary<string, object>();
			var sqlInstruction = EntitySqlParser.ParseEntityPaged(filterEntity, engine, action, filterEntity,
				offset, pageSize, filterConjunction, groupAttributes: groupAttributes,
				sortAttributes: sortAttributes, orderDescending: orderDescending,
				readUncommited: _readUncommied, sqlParameters: sqlParameters, aggregates: aggregates);

			IEnumerable<object> returnList = null;

			if (((connection != null) && keepConnection) || base.Connect())
			{
				returnList = await ExecuteQueryAsync(filterEntity.GetType(), sqlInstruction, sqlParameters);
			}

			if (!keepConnection) base.Disconnect();

			return returnList ?? new List<object>();
		}

		internal async Task<int> CountObject(object filterEntity)
		{
			int result = 0;
			var sqlParameters = new Dictionary<string, object>();
			var sqlInstruction = EntitySqlParser.ParseEntity(filterEntity, engine, PersistenceAction.Count,
				filterEntity, sqlParameters: sqlParameters);

			if (keepConnection || Connect())
			{
				var dapperParams = sqlParameters.ToDictionary(k => (object)k.Key, v => v.Value);
				result = await ExecuteCommandAsync(sqlInstruction, dapperParams);
			}

			if (!keepConnection) Disconnect();

			return result;
		}

		internal int CountObjectSync(object filterEntity)
			=> CountObject(filterEntity).Result;

		#endregion

		#region Private — Write helpers

		private async Task<int> AddObject(object entity, bool persistComposition,
			string optionalConnConfig = "", bool isReplicating = false)
		{
			string sqlInstruction;
			int lastInsertedId = 0;

			var entityType = entity.GetType();
			var entityProps = entityType.GetProperties();

			if (keepConnection || base.Connect(optionalConnConfig))
			{
				var entityKeyProp = EntityReflector.GetKeyColumn(entityProps);
				if (entityKeyProp != null && entityKeyProp.PropertyType == typeof(Guid)
					&& EntityReflector.IsAutoGenerated(entityKeyProp))
				{
					entityKeyProp.SetValue(entity, Guid.NewGuid());
				}

				sqlInstruction = EntitySqlParser.ParseEntity(entity, engine, PersistenceAction.Add);

				if (persistComposition)
					base.StartTransaction();

				lastInsertedId = await ExecuteCommandAsync(sqlInstruction);

				if (entityKeyProp != null && entityKeyProp.PropertyType != typeof(Guid) && lastInsertedId > 0)
					entityKeyProp.SetValue(entity, lastInsertedId);

				if (persistComposition)
					PersistComposition(entity, PersistenceAction.Add);
				else
					if (!keepConnection) base.Disconnect();
			}

			CleanCacheableData(entity);

			if (replicationEnabled && !isReplicating)
				AddReplicas(entity, entityProps, lastInsertedId, persistComposition);

			return lastInsertedId;
		}

		private int AddObjectSync(object entity, bool persistComposition,
			string optionalConnConfig = "", bool isReplicating = false)
			=> AddObject(entity, persistComposition, optionalConnConfig, isReplicating).GetAwaiter().GetResult();

		private async Task<int> UpdateObject(object entity, object filterEntity, bool persistComposition,
			string optionalConnConfig = "", bool isReplicating = false)
		{
			int recordsAffected = 0;
			string sqlInstruction;

			var entityType = entity.GetType();
			var entityProps = entityType.GetProperties();

			if (keepConnection || base.Connect(optionalConnConfig))
			{
				sqlInstruction = EntitySqlParser.ParseEntity(entity, engine, PersistenceAction.Update, filterEntity);

				if (persistComposition)
					base.StartTransaction();

				recordsAffected = await ExecuteCommandAsync(sqlInstruction);

				if (persistComposition)
					PersistComposition(entity, PersistenceAction.Update, filterEntity);
				else
				if (!keepConnection) base.Disconnect();
			}

			CleanCacheableData(entity);

			if (base.replicationEnabled && !isReplicating)
				UpdateReplicas(entity, filterEntity, entityProps, persistComposition);

			return recordsAffected;
		}

		private int UpdateObjectSync(object entity, object filterEntity, bool persistComposition,
			string optionalConnConfig = "", bool isReplicating = false)
			=> UpdateObject(entity, filterEntity, persistComposition, optionalConnConfig, isReplicating).GetAwaiter().GetResult();

		private async Task<int> RemoveObjects(object filterEntity,
			string optionalConnConfig = "", bool isReplicating = false)
		{
			string sqlInstruction;
			int recordsAffected = 0;

			var entityType = filterEntity.GetType();
			var entityProps = entityType.GetProperties();

			if (keepConnection || base.Connect(optionalConnConfig))
			{
				sqlInstruction = EntitySqlParser.ParseEntity(filterEntity, engine, PersistenceAction.Remove, filterEntity);

				recordsAffected = await ExecuteCommandAsync(sqlInstruction);

				PersistComposition(filterEntity, PersistenceAction.Remove);

				if (!keepConnection) base.Disconnect();
			}

			CleanCacheableData(filterEntity);

			if (base.replicationEnabled && !isReplicating)
				RemoveReplicas(filterEntity, entityProps);

			return recordsAffected;
		}

		private int RemoveObjectsSync(object filterEntity,
			string optionalConnConfig = "", bool isReplicating = false)
			=> RemoveObjects(filterEntity, optionalConnConfig, isReplicating).GetAwaiter().GetResult();

		#endregion

		#region Private — Composition

		private void FillComposition(object loadedEntity, PropertyInfo[] entityProps)
		{
			var entityType = loadedEntity.GetType();

			if (_visitedTypes == null)
				_visitedTypes = new Dictionary<Type, int>();

			if (_visitedTypes.TryGetValue(entityType, out int count) && count >= 2)
				return;

			_visitedTypes[entityType] = count + 1;

			try
			{
				FillCompositionInternal(loadedEntity, entityProps);
			}
			finally
			{
				if (_visitedTypes[entityType] <= 1)
					_visitedTypes.Remove(entityType);
				else
					_visitedTypes[entityType]--;
			}
		}

		private void FillCompositionInternal(object loadedEntity, PropertyInfo[] entityProps)
		{
			var childEntities = EntityReflector.GetRelatedEntities(entityProps);

			foreach (var child in childEntities)
			{
				Type childEntityType = child.PropertyType;
				bool childEntityIsList = typeof(IEnumerable).IsAssignableFrom(childEntityType) && childEntityType != typeof(string);
				if (childEntityIsList && childEntityType.IsGenericType)
					childEntityType = child.PropertyType.GetGenericArguments()[0];

				PropertyInfo[] childProps = childEntityType.GetProperties();
				object childEntityInstance = Activator.CreateInstance(childEntityType, true);
				RelatedEntityAttribute relationAttrib = EntityReflector.GetRelatedEntityAttribute(child);
				var keyColumn = EntityReflector.GetKeyColumn(entityProps);

				switch (relationAttrib.Cardinality)
				{
					case RelationCardinality.OneToOne:
						if (EntityReflector.SetChildForeignKeyValue(loadedEntity, entityProps, childEntityInstance,
																	childProps, relationAttrib.ForeignKeyAttribute))
							childEntityInstance = GetObjectSync(childEntityInstance, true);
						break;

					case RelationCardinality.ManyToOne:
						if (EntityReflector.SetParentForeignKeyValue(loadedEntity, entityProps, childEntityInstance,
																	 childProps, relationAttrib.ForeignKeyAttribute))
							childEntityInstance = GetObjectSync(childEntityInstance, true);
						break;

					case RelationCardinality.OneToMany:
						childProps = childEntityType.GetProperties();
						if (EntityReflector.SetChildForeignKeyValue(loadedEntity, entityProps, childEntityInstance,
																	childProps, relationAttrib.ForeignKeyAttribute))
							childEntityInstance = QueryObjectsSync(childEntityInstance, PersistenceAction.Query, true);
						else
							childEntityInstance = null;
						break;

					case RelationCardinality.ManyToMany:
						var intermedyEntityInstance = Activator.CreateInstance(relationAttrib.IntermediaryEntity, true);
						var intermedyEntityProps = intermedyEntityInstance.GetType().GetProperties();

						if (intermedyEntityInstance != null)
						{
							if (EntityReflector.SetChildForeignKeyValue(loadedEntity, entityProps, intermedyEntityInstance,
																		intermedyEntityProps, relationAttrib.IntermediaryKeyAttribute))
							{
								var manyToManyRelations = QueryObjectsSync(intermedyEntityInstance, PersistenceAction.Get);
								var manyToManyResultList = EntityReflector.CreateTypedList(child);

								foreach (var relationInstance in manyToManyRelations)
								{
									if (EntityReflector.SetParentForeignKeyValue(relationInstance, intermedyEntityProps,
																				 childEntityInstance, childProps,
																				 relationAttrib.ForeignKeyAttribute))
									{
										var childRelationInstance = GetObjectSync(childEntityInstance);
										manyToManyResultList.Add(childRelationInstance);
									}
								}

								childEntityInstance = manyToManyResultList;
								childEntityIsList = false;
							}
						}
						break;
				}

				SetParentChildEntity(loadedEntity, child, childEntityInstance, childEntityIsList);
			}
		}

		private void SetParentChildEntity(object loadedEntity, PropertyInfo child,
			object childEntityInstance, bool childEntityIsList)
		{
			if (childEntityInstance == null) return;
			if (!child.CanWrite) return;

			if (!childEntityIsList)
				child.SetValue(loadedEntity, childEntityInstance, null);
			else
			{
				var childListInstance = (IList)childEntityInstance;
				if (childListInstance.Count > 0)
				{
					var childTypedList = EntityReflector.CreateTypedList(child);
					foreach (var listItem in childListInstance)
						childTypedList.Add(listItem);
					child.SetValue(loadedEntity, childTypedList, null);
				}
			}
		}

		private List<string> ParseComposition(object entity, PersistenceAction action, object filterEntity)
		{
			List<string> result = new List<string>();
			var childEntities = EntityReflector.GetRelatedEntities(entityProps);

			foreach (PropertyInfo child in childEntities)
			{
				object childEntityInstance;
				object childEntityFilter = null;

				var relationAttrib = EntityReflector.GetRelatedEntityAttribute(child);
				childEntityInstance = child.GetValue(entity, null);
				var entityParent = entity;

				if (childEntityInstance != null)
				{
					var childEntityType = childEntityInstance.GetType();
					if (!(childEntityInstance is IList) && !childEntityType.Name.Contains("List") && !childEntityType.Name.Contains("ReadOnlyCollection"))
					{
						var childProps = childEntityType.GetProperties();
						action = EntitySqlParser.SetPersistenceAction(childEntityInstance, EntityReflector.GetKeyColumn(childProps));

						if (action == PersistenceAction.Update)
						{
							childEntityFilter = Activator.CreateInstance(childEntityInstance.GetType());
							EntityReflector.SetFilterPrimaryKey(childEntityInstance, childProps, childEntityFilter);
						}

						if (relationAttrib.Cardinality == RelationCardinality.OneToOne)
							EntityReflector.SetChildForeignKeyValue(entityParent, entityProps, childEntityInstance,
															   childProps, relationAttrib.ForeignKeyAttribute);
						else
							EntityReflector.SetChildForeignKeyValue(childEntityInstance, childProps, entityParent,
															   entityProps, relationAttrib.ForeignKeyAttribute);

						result.Add(EntitySqlParser.ParseEntity(childEntityInstance, engine, action));
					}
					else
					{
						var childListInstance = (IList)childEntityInstance;
						List<object> childFiltersList = new List<object>();

						if (childListInstance.Count > 0)
						{
							foreach (var listItem in childListInstance)
							{
								var listItemType = listItem.GetType();
								var listItemProps = listItemType.GetProperties();

								if (relationAttrib.Cardinality == RelationCardinality.OneToMany)
								{
									EntitySqlParser.ParseOneToManyRelation(childEntityFilter, listItem, listItemType,
																		   listItemProps, ref action, childFiltersList);
									EntityReflector.SetChildForeignKeyValue(entityParent, entityProps, listItem, listItemProps, relationAttrib.ForeignKeyAttribute);
									result.Add(EntitySqlParser.ParseEntity(listItem, engine, action));
								}
								else
								{
									var manyToEntity = EntitySqlParser.ParseManyToRelation(listItem, relationAttrib);
									EntityReflector.SetChildForeignKeyValue(entityParent, entityProps, manyToEntity, listItemProps, relationAttrib.ForeignKeyAttribute);
									var existRelation = GetObject(manyToEntity);
									if (existRelation != null) manyToEntity = existRelation;
									var manyToEntityProps = manyToEntity.GetType().GetProperties();
									action = EntitySqlParser.SetPersistenceAction(manyToEntity, EntityReflector.GetKeyColumn(manyToEntityProps));
									object existFilter = null;
									if (action == PersistenceAction.Update)
									{
										existFilter = Activator.CreateInstance(manyToEntity.GetType());
										EntityReflector.SetFilterPrimaryKey(manyToEntity, manyToEntityProps, existFilter);
										childFiltersList.Add(existFilter);
									}
									result.Add(EntitySqlParser.ParseEntity(manyToEntity, engine, action));
								}
							}
						}
						else
						{
							var childInstance = Activator.CreateInstance(childListInstance.GetType().GetGenericArguments()[0]);
							object childEntity;
							if (relationAttrib.Cardinality == RelationCardinality.ManyToMany)
								childEntity = EntitySqlParser.ParseManyToRelation(childInstance, relationAttrib);
							else
								childEntity = childInstance;

							var childProps = childEntity.GetType().GetProperties();
							EntityReflector.SetChildForeignKeyValue(entityParent, entityProps, childEntity, childProps, relationAttrib.ForeignKeyAttribute);
							childFiltersList.Add(childEntity);
						}
					}
				}
			}

			return result;
		}

		private void PersistComposition(object entity, PersistenceAction action, object filterEntity = null)
		{
			try
			{
				List<string> childEntityCommands = ParseComposition(entity, action, filterEntity);

				foreach (var cmd in childEntityCommands)
					ExecuteCommand(cmd);

				if (base.transactionControl != null)
					base.CommitTransaction();

				base.Disconnect();
				CleanCacheableData(entity);
			}
			catch (Exception)
			{
				if (base.transactionControl != null)
					base.CancelTransaction();
				base.Disconnect();
			}
		}

		#endregion

		#region Private — Replicas

		private void AddReplicas(object entity, PropertyInfo[] entityProps, int lastInsertedId, bool persistComposition)
		{
			var entityColumnKey = EntityReflector.GetKeyColumn(entityProps);
			if (entityColumnKey != null)
				entityColumnKey.SetValue(entity, lastInsertedId, null);

			ParallelParam parallelParam = new ParallelParam()
			{
				Param1 = entity,
				Param2 = PersistenceAction.Add,
				Param3 = persistComposition
			};

			var replicationParallelDelegate = new ParameterizedThreadStart(PersistReplicasAsync);
			Parallelizer.StartNewProcess(replicationParallelDelegate, parallelParam);
		}

		private void UpdateReplicas(object entity, object filterEntity, PropertyInfo[] entityProps, bool persistComposition)
		{
			ParallelParam parallelParam = new ParallelParam()
			{
				Param1 = entity,
				Param2 = PersistenceAction.Update,
				Param3 = persistComposition,
				Param4 = filterEntity
			};

			var replicationParallelDelegate = new ParameterizedThreadStart(PersistReplicasAsync);
			Parallelizer.StartNewProcess(replicationParallelDelegate, parallelParam);
		}

		private void RemoveReplicas(object filterEntity, PropertyInfo[] entityProps)
		{
			ParallelParam parallelParam = new ParallelParam()
			{
				Param1 = filterEntity,
				Param2 = PersistenceAction.Remove
			};

			var replicationParallelDelegate = new ParameterizedThreadStart(PersistReplicasAsync);
			Parallelizer.StartNewProcess(replicationParallelDelegate, parallelParam);
		}

		private void PersistReplicasAsync(object param)
		{
			try
			{
				foreach (var connString in _replicaConnStrings)
				{
					ParallelParam parallelParam = param as ParallelParam;

					object entity = parallelParam.Param1;
					PersistenceAction action = (PersistenceAction)parallelParam.Param2;

					bool persistComposition = false;
					if (parallelParam.Param3 != null)
						persistComposition = (bool)parallelParam.Param3;

					object filterEntity = null;
					if (parallelParam.Param4 != null)
						filterEntity = parallelParam.Param4;

					using (var repos = new GenericRepository<T>(engine, _connString))
					{
						switch (action)
						{
							case PersistenceAction.Add:
								repos.AddSync((T)entity, persistComposition);
								break;
							case PersistenceAction.Update:
								repos.UpdateSync((T)entity, (T)filterEntity, persistComposition);
								break;
							case PersistenceAction.Remove:
								repos.RemoveSync((T)filterEntity);
								break;
						}
					}
				}
			}
			catch (Exception ex)
			{
				RegisterException("PersistReplicas", ex, param);
			}
		}

		#endregion

		#region Private — Cache

		private bool IsCacheable(object entity)
		{
			var hasCacheAttrib = (entity.GetType().GetCustomAttribute(typeof(CacheableAttribute)) != null);
			return (hasCacheAttrib && _cacheProvider != null);
		}

		private void CleanCacheableData(object entity)
		{
			var isCacheable = (entity.GetType().GetCustomAttribute(typeof(CacheableAttribute)) != null);
			if (isCacheable && (_cacheProvider != null))
				_cacheProvider.Del(entity, true);
		}

		#endregion

		#region Private — Logging

		private void RegisterException(string operationName, Exception exception, object content)
		{
			var logFileName = string.Format("{0}\\{1}_{2}_{3}.log", _logPath, operationName, content.GetHashCode(), DateTime.Now.Ticks);
			var exceptionContent = string.Format("Exception : {0}{1}{2} Content : {3}", JsonSerializer.Serialize(exception), Environment.NewLine, Environment.NewLine, JsonSerializer.Serialize(content));
			File.WriteAllText(logFileName, exceptionContent);
		}

		#endregion
	}
}
