using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;

namespace Rochas.DapperRepository.Test
{
    [Table("dim_customer")]
    public class DimCustomerEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Filterable]
        [Column("customer_name")]
        public string CustomerName { get; set; }

        [Column("region")]
        public string Region { get; set; }
    }
}
