using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;

namespace Rochas.DapperRepository.Test
{
    [Table("fact_sales")]
    public class FactSalesDictionaryEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("product_id")]
        public int ProductId { get; set; }

        [Column("quantity")]
        public int Quantity { get; set; }

        [Column("total_amount")]
        public decimal TotalAmount { get; set; }
    }
}
