using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;

namespace Rochas.DapperRepository.Test
{
    [Table("fact_sales")]
    public class FactSalesEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("sale_date")]
        public string SaleDate { get; set; }

        [Column("product_id")]
        public int ProductId { get; set; }

        [Column("customer_id")]
        public int CustomerId { get; set; }

        [Column("quantity")]
        public int Quantity { get; set; }

        [Column("unit_price")]
        public decimal UnitPrice { get; set; }

        [Column("total_amount")]
        public decimal TotalAmount { get; set; }

        [RelationalColumn(
            TableName = "dim_product",
            ColumnName = "product_name",
            ColumnAlias = "ProductName",
            KeyColumn = "product_id",
            ForeignKeyColumn = "id",
            JunctionType = RelationalJunctionType.Mandatory)]
        public string ProductName { get; set; }

        [RelationalColumn(
            TableName = "dim_customer",
            ColumnName = "customer_name",
            ColumnAlias = "CustomerName",
            KeyColumn = "customer_id",
            ForeignKeyColumn = "id",
            JunctionType = RelationalJunctionType.Mandatory)]
        public string CustomerName { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Sum)]
        public decimal SumTotalAmount { get; set; }

        [DataAggregationColumn(ColumnName = "id", AggregationType = DataAggregationType.Count)]
        public int CountSales { get; set; }

        [DataAggregationColumn(ColumnName = "unit_price", AggregationType = DataAggregationType.Average)]
        public decimal AvgUnitPrice { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Maximum)]
        public decimal MaxTotalAmount { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Minimum)]
        public decimal MinTotalAmount { get; set; }
    }
}
