using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;

namespace Rochas.DapperRepository.Test
{
    [Table("sample_many_foreign_entity")]
    public class SampleManyForeignEntity : SampleForeignEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("parent_id")]
        public int? ParentId { get; set; }

        [Column("creation_date")]
        public DateTime CreationDate { get; set; }

        [Column("active")]
        public bool Active { get; set; }
    }
}
