using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;

namespace Rochas.DapperRepository.Test
{
    [Table("sample_guid_entity")]
    public class SampleGuidEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public Guid Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("active")]
        public bool Active { get; set; }
    }
}
