using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;

namespace Rochas.DapperRepository.Test
{
    [Table("sample_invoice_entity")]
    public class SampleInvoiceEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("invoice_number")]
        public string InvoiceNumber { get; set; }

        [Column("customer_id")]
        public int CustomerId { get; set; }

        [Column("total_amount")]
        public decimal TotalAmount { get; set; }

        [Column("active")]
        public bool Active { get; set; }

        private readonly List<SampleInvoiceItemEntity> _items = new();

        public IReadOnlyCollection<SampleInvoiceItemEntity> Items => _items.AsReadOnly();

        public void AddItem(SampleInvoiceItemEntity item)
        {
            _items.Add(item);
            TotalAmount += item.LineTotal;
        }

        public void ClearItems()
        {
            _items.Clear();
            TotalAmount = 0;
        }
    }

    [Table("sample_invoice_item_entity")]
    public class SampleInvoiceItemEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("invoice_id")]
        public int InvoiceId { get; set; }

        [Column("product_name")]
        public string ProductName { get; set; }

        [Column("quantity")]
        public int Quantity { get; set; }

        [Column("unit_price")]
        public decimal UnitPrice { get; set; }

        [Column("line_total")]
        public decimal LineTotal { get; set; }
    }
}
