using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;

namespace Rochas.DapperRepository.Test
{
    [Table("sample_guid_array_entity")]
    public class SampleGuidArrayEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public Guid Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Filterable]
        [Column("tags")]
        public string[] Tags { get; set; }

        [Column("hash_codes")]
        public uint[] HashCodes { get; set; }

        [Column("active")]
        public bool Active { get; set; }
    }
}
